name: Release Workflow

on:
  push:
    branches:
      - ci
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"

      - name: Install dependencies
        run: helm dependency update charts/hello-world

      - name: Package chart
        run: helm package charts/hello-world -d ./helm

  release:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4" # Spécifiez la version de Helm à utiliser

      - name: Extract chart version
        id: version
        run: |
           echo "::set-output name=version::$(grep -m1 '^version: ' charts/hello-world/Chart.yaml | awk '{print $2}')"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./charts/*
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            test release
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
