name: Release Workflow

on:
  push:
    branches:
      - ci

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.5.4"

      - name: Install dependencies and package charts
        run: |
          for dir in $(find charts/hello-world -mindepth 1 -maxdepth 1 -type d); do
            version=$(basename "$dir")
            helm dependency update "$dir"
            helm package "$dir" -d ./helm --version "$version"
          done

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/CHANGELOG.txt
          files: |
            ${{ github.workspace }}/helm/*.tgz
          tag_name: tag
          name: Helm-test-Realease
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

